input_dim = 500
hidden_dim = 32
n_labels = 126
local_layers = 2
dropout = 0.5
heads = 8
pre_linear = True
res = True
ln = True
bn = False
jk = True
gnn = "gat"
x_res = True
halfhop = True
xyz_status = True
model_type = "gnn"
n_mask = 5
lr = 0.075 
n_epochs = 1000