expname: "default"

data:
  name: "one_hemisphere"
  file_names:
    - "test_one_section_hemi.h5ad"
  n_genes: 500
  n_labels: 158
  cell_type: "subclass"
  spatial_coords:
    - "x_section"
    - "y_section"
    - "z_section"
  self_loops_only: false
  batch_size: 5
  n_hops: 2
  num_workers: 16
  d_threshold: 1000
  n_splits: 5
  cv: 0
  rand_seed: 42

model:
  name: "antelope"
  gene_ch: ${data.n_genes}
  spatial_ch: 3 # should match length of spatial_coords
  hid_ch: 32
  out_ch: ${data.n_labels}
  n_select: 10
  local_layers: 2
  dropout: 0.5
  heads: 1
  pre_linear: true
  res: true
  ln: true
  bn: false
  jk: true
  x_res: true
  gnn: "gat"
  xyz_status: true
  halfhop: true

logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  on_step: false
  on_epoch: true
  prog_bar: true
  logger: true

trainer:
  limit_train_batches: 1000
  limit_val_batches: 100
  max_epochs: 200
  lr: 0.001
  lr_scheduler: "constant"

hydra:
  run:
    dir: "../../data/hydralogs/"
